[tool.poetry]
name = "signal-protocol"
version = "0.1.0"
description = ""
authors = ["Ryan Scott <rscott@galois.com>"]

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.33.0"
BitVector = "^3.4.9"
saw-client = "^1.5.0"
# Add a fake dep on urllib3 (we don't directly depend on it but
# some of the above packages do) to add a constraint for a security
# issue.
urllib3 = ">=2.7.0"
# Add a fake dep on idna (we don't directly depend on it but
# some of the above packages do) to add a constraint for a security
# issue.
idna = ">=3.15"

[tool.poetry.dev-dependencies]
mypy = "^1.10"
isort = "^5.7.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
