name: saw-demos

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  SOLVER_PKG_VERSION: "snapshot-20260622"
  SAW_VERSION: "1.5"
  LLVM_CONFIG: "llvm-config-18"

jobs:
  run-demos:
    runs-on: ${{ matrix.os }}
    name: saw-demos (${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
    - name: "Checkout"
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Download what4-solvers
      uses: GaloisInc/what4-solvers@v1
      with:
        dest: bin
        release: ${{ env.SOLVER_PKG_VERSION }}

    - name: "Install system dependencies"
      shell: bash
      run: |
        .github/ci.sh install_system_deps

    - name: "Install Python"
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: "Install Poetry"
      uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: 1.1.5

    - name: "Install wllvm"
      shell: bash
      run: pip install wllvm

    - name: "Run demos"
      shell: bash
      run: |
        export PATH="$PWD/bin:$PATH"
        make -C templates/c
        make -C demos/salsa20
        make -C demos/signal-protocol
        make -C demos/signal-protocol all-python
        make -C demos/xxhash
